### ISSUE TITLE
The readme file is pretty sparse

### ISSUE THREAD

**Issue by L-Walker** [nocarryr/rtlsdr-wwb-scanner#12]
I installed the pre requisite library and the wwb setup debug showed it installed correctly, be it with some path warnings. But your readme says stuff all on how to actually run the code, can you please elaborate a bit more in the documentation please? Not all of us are high level python users.

**Comment by nocarryr** [comment]
I agree completely.  The README isn't very clear and overall documentation for this project needs a lot of work.

I just looked in my local copy and found that I did add some more info on installing and running a few months ago.  I'll commit and push that in a few minutes.  Hopefully it helps
