### ISSUE TITLE
numpy update breaks scan

### ISSUE THREAD

**Issue by DiggiD** [nocarryr/rtlsdr-wwb-scanner#13]
phase_rot = np.fromiter(iter_phase(), dtype=np.float)
Attribute Error: Module 'numpy' has no attribute 'float'

**Comment by nocarryr** [comment]
Good catch!  I've noticed numpy removed the generic `float` and `int` dtype aliases in working on other projects.

https://github.com/nocarryr/rtlsdr-wwb-scanner/blob/eb57fa740b487e6ae85cf122031f042abae0d103/wwb_scanner/scanner/sample_processing.py#L105

Afaik, the line above can be changed to:

```python
phase_rot = np.fromiter(iter_phase(), dtype=np.float64)
```

If you'd like to drop that in and test it out, I'd gladly except a pull request

**Comment by DiggiD** [comment]
done, tested, works!

sending pull request
